### PR TITLE
Added to UserProfiles, View All User Profiles

### PR DESCRIPTION
**Pull request by theljwhite**
# Description

Given that a user is authorized and is an administrator, when they click on the User Profiles affordance in the navigation bar, they are taken to a page where a list of all user profiles are displayed alphabetically by Display Name. This lays the foundation for profiles to be able to be managed from this route by admin users at a later date. This also adds a UserProfileController and other elements for later use in development. 

Fixes # (issue)

- [Trello Ticket - "#23 View All User Profiles" ](https://trello.com/c/jKfkxyV4l)

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# Testing Instructions

First, make sure you retrieve my branch by running `git fetch --all` in your terminal and then switching to my branch by running `git checkout feat-user-profiles`.

Make sure that you have this repo cloned into a local repository and have added your database using the `.sql` files in the SQL folder. You can do this by right clicking your `TabloidMVC` database, select New Query, and paste and run the following files in order:

[01_TabloidMVC_Create_DB.sql](https://github.com/NewForce-Cohort-9/tabloidmvc-hot-chubb-time-machine/blob/main/SQL/01_TabloidMVC_Create_DB.sql)
[02_TabloidMVC_Seed_Data.sql](https://github.com/NewForce-Cohort-9/tabloidmvc-hot-chubb-time-machine/blob/main/SQL/02_TabloidMVC_Seed_Data.sql)
[03_TabloidMVC_Add_More_Users.sql](https://github.com/NewForce-Cohort-9/tabloidmvc-hot-chubb-time-machine/pull/1/commits/7bba5cc398097eb5f755e18de9b2d95860d9859e)

The 3rd file will add 2 more users so that you can verify that user profiles are displayed alphabetically. It is also included with this PR.  You can create a new query by right clicking your `TabloidMVC` database in Visual Studio. Run a select statement `SELECT * FROM UserProfile` to ensure that your database is working and has sufficient users added.

1. Have the `TabloidMVC.sln` solution opened in Visual Studio. Ensure that you followed the steps above. 
2. Run the program to start your web browser. If you are logged in by default, you will want to log out by clicking the navbar affordance for logout and re-log in as an administrator using the email `admin@example.com`.  It is crucial that you re-log in, even if you are already logged in as the admin user.

3. Once you are logged in as an admin, you should see the User Profiles affordance in the navbar. This will take you to the `/UserProfile` route (the Index view for UserProfile). Click on it and ensure that you see a list of all user profiles sorted alphabetically by display name. You should see the admin user and the new user(s) you added. 

# Checklist:

- [x] I have my database set up and I have opened the `feat-user-profiles` branch in my local repository.
- [x] I have run the SQL queries to view and add new users to my database. 
- [x] I have verified that a new user was added to my database. 
- [x] I have verified that I have logged out and logged back in as admin user `admin@example.com`
- [x] When logged in, I can see User Profiles affordance in the navbar.
- [x] When I click on User Profiles, I should see a list of users sorted alphabetically by display name.

### CODE REVIEW

**Comment by aw315** [comment]
Great job! By following your instructions, I was able to add a new user to the database and see the list of all users when I selected 'User Profiles'. Your instructions were easy to follow and made it easy for me to know that I had tested it appropriately. 👍

**Comment by C-Red20** [comment]
App works as stated for ticket. Instructions were detailed and I was able to do as directed.

**Review by Tommy-Spurlock — CHANGES_REQUESTED** [review]
These steps seem a bit confusing and also unnecessary:

```
In order to test that the user profiles are displayed alphabetically, you will need to run a SQL query in order to add more users to your database. Verify that your database is created from the steps above and that you have the admin@example.com user. Create a new query in Visual Studio for your database by right clicking it.

In the new query, type SELECT * FROM UserProfile and highlight the code and run it. Based on the last Id number that you see, add 1 to that number. Under the select statement, paste the following code below to add a user. Based on the Id number, you will want to change the number 3 in the query below to whatever your next Id is.

SET IDENTITY_INSERT [UserProfile] ON
INSERT INTO [UserProfile] ( [Id], [FirstName], [LastName], [DisplayName], [Email], [CreateDateTime], [ImageLocation], [UserTypeId]) VALUES (3, 'Zimbo30', 'Johnson', 'Zimbo', 'fake@example.com', SYSDATETIME(), NULL, 2); 
SET IDENTITY_INSERT [UserProfile] OFF
Highlight the code and run it. You should see a success message that 1 row was affected. You can repeat this step as many times as you would like to add more users - you will just need to make sure that you have the correct next Id number and you can change the display name, first name, last name values if you wish.
```

A better approach to this is to crate a new SQL script and  have it run in succession to the first two. It should include multiple instances of new users. These changes would make your instructions more clear and allow your testers to move more efficiently.

**Review by Tommy-Spurlock — APPROVED** [review]
Requested changes look good. There are extra steps sprinkled into the instructions that you don't need and make it more confusing for a tester. I'll approve this one,  just make sure to clean the next PR up a bit more.

**Pull request merged**
