### PR TITLE
Cl branch ticket9

### PR DESCRIPTION
**Pull request by C-Red20**
# Description

Created a new Nav location on the Nav bar for Categories. When clicked it will take you to a List of the categories available to use in alphabetical order.

Fixes # (issue)
[Ticket #9](https://trello.com/c/1uvVMmch)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Testing Instructions

1. Clone down the repository.
2. git fetch -a
3. git checkout cl-branch-ticket9
4. git pull any changes that have been made if needed. 
5. Navigate to the root directory for this repo (directory-to)/tabloidmvc-hot-chubb-time-machine
6. Open TabloidMVC.sln in Visual Studio Code.
7. Make sure your database is created with seed data. Here is the [Seed Data](https://github.com/NewForce-Cohort-9/tabloidmvc-hot-chubb-time-machine/tree/main/SQL) if you need it.
8. Click the execute with debugger solid green button to launch the app.
9. Log in as admin [admin@example.com](mailto:admin@example.com) (if not already logged in as admin).
10. Click Categories at the top of the page.
11. Then you should see the Categories Listed in alphabetical order.

To test if Categories is correct and in alphabetical order run a SQL Query with the following code.
`SELECT id, name FROM Category ORDER BY Name`

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by theljwhite** [comment]
Works as described per your instructions. Categories now shows up in the navbar. When you go to the `/Category` route, you can see the categories listed in alphabetical order. Nice!

**Comment by aw315** [comment]
Nice job, works as intended and the instructions were easy to follow.

**Review by sarahebrooks12 — CHANGES_REQUESTED** [review]
So our testing instructions need to be thorough and written out for someone who isn't familiar with your project. Please look at the gist for examples. 

Please remind them to perform any git commands needed - so first step could be clone down repository or if you have access then git add and git commit the branch you're working on your branch.

Add link to create data with your seed data:
Make sure your DB is [created and seeded](https://github.com/NewForce-Cohort-9/tabloidmvc-hot-chubb-time-machine/tree/main/SQL)

Instead of start the server - 
Click the execute with debugger solid green button to launch the app

Make sure to list out the data or provide a SQL query that would show the tester exactly how the data should appear in the browser. So if alphabetical categories then list all categories alphabetical or include the SQL query you have in your repo for them to run

**Review by sarahebrooks12 — APPROVED** [review]
Looks good! Just remember to be thorough

**Pull request merged**
