### PR TITLE
Created Delete Post option per ticket #7

### PR DESCRIPTION
**Pull request by MichaelPAdkins**
# Description

Created the ability to delete.  This includes the opportunity to cancel or confirm deletion prior to finalizing your choice.

Fixes # (issue)
[Ticket #7](https://trello.com/c/EY9NBm8E)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Testing Instructions

1. Clone down the repository.
2. git fetch -a
3. git checkout PostDeleteMA1
4. git pull any changes that have been made if needed. 
5. Navigate to the root directory for this repo (directory-to)/tabloidmvc-hot-chubb-time-machine
6. Open TabloidMVC.sln in Visual Studio Code.
7. Make sure your database is created with seed data. Here is the [Seed Data](https://github.com/NewForce-Cohort-9/tabloidmvc-hot-chubb-time-machine/tree/main/SQL) if you need it.
8. Click the execute with debugger solid green button to launch the app.
9. Log in as admin [admin@example.com](mailto:admin@example.com) (if not already logged in as admin).
10. Click Posts at the top of the page.
11. Then you should see the sample post.
12. Below the bold Posts heading, you'll see a blue button saying "New Post".  
13. Click the blue "New Post" button.
14. Below the heading "What do you have to say?" you will see five fields that will accept input: Title, Header Image URL, Published, Category, and Content.
15. In each field enter the appropriate data.  "TItle" and "Content will accept whatever characters you wish to enter.  "Header Image URL" will accept any textual input, but best practice is to enter the URL for any photo being hosted online so you can see it functions correctly.
16. You may enter the numberals manually in the "Published" field, or you may click the calendar icon on the fir right of the field to select the appropriate date in the pop-up that is displayed.
17. Clicking the "Category" field will allow you to choose from a number of premade options from a pop-up.
18. Now that you have entered the data in the various fields for your post, click the blue "Save" button at the bottom of the field where you entered your Content.
19. This takes you to the expanded view for your post where you are shown the options to edit (by clicking the currently non functional pencil icon) or delete your post by clicking the trashcan icon.
20. To return to the list of posts in chronological order, click the Posts subheading at the top of the screen (or skip to step 22. to learn how to delete the post).
21. From the list of Posts, you may click on the trashcan icon (representing the delete option) from the unexpanded post, or click the eye icon to open the post.  Just like when you initially saved your post, you will see the trashcan icon is the second icon available below the Title, Category, and published date subheadings.
22. Click on the trashcan icon.  You will see a red Delete button and a grey Cancel button.  
23. Clicking Delete will return you to the Posts page where you will see it has been deleted.  Clicking Cancel will return you to the Posts page and you will see it remains unchanged.  

To test if deleting posts from the Posts page is possible, please feel free to create a new post and then delete it, or delete the sample post.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by C-Red20** [comment]
I can delete my trash posts yay

**Comment by theljwhite** [comment]
Deleting posts/delete post confirmation & other elements are worked as expected, nice!

**Review by sarahebrooks12 — CHANGES_REQUESTED** [review]
We want to protect our seed data so make sure you have the tester create a Post before they delete it. 
Create a post with the title of testing
Select the post with the title of testing
Hit the trash can button
...etc

**Comment by MichaelPAdkins** [comment]
I've further explicated the steps for deleting a post.  This way, if anything deviates from the page view described in the directions, it might be an indication there are bugs or code conflicts that need to be addressed.

**Review by sarahebrooks12 — APPROVED** [review]
Looks good!

**Pull request merged**
