### PR TITLE
Tag Management now lists Tags

### PR DESCRIPTION
**Pull request by aw315**
# Description

'Tag Management' option added to the NavBar.

When you select the 'Tag Management' option in the NavBar, you will be taken to a list of the Tags in the database listed in alphabetical order. 

[Ticket #13](https://trello.com/b/jR1QUhwC/hot-chubb-time-machine) from our Trello Board

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# Testing Instructions

Make sure you have cloned this repository.
Run 'git fetch --all' in your terminal to check my changes in your local repository. 
Run 'git checkout andrew-branch' to switch to my branch so that you can test my work. 
Navigate to the root directory for this repository (directory-to)/tabloidmvc-hot-chubb-time-machine
Start TabloidMVC.sln
Make sure your database has been created with the [Seed Data](https://github.com/NewForce-Cohort-9/tabloidmvc-hot-chubb-time-machine/tree/main/SQL)
In your 'SQL Server Object Explorer', right-click on 'TabloidMVC' and select 'New Query'
Paste the following text into the query and run the query to list all the Tags in the Database: "SELECT * FROM Tag ORDER BY Name" - this should present the list in alphabetical order
Once you have checked the list of Tags, start the server by clicking the Green Play Button with TabloidMVC next to it
If you are not already logged in, use the email "admin@example.com" to login
Click 'Tag Management' at the top of the page
Make sure that the tags are listed and in alphabetical order

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings or errors
- [ ] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by theljwhite** [comment]
Everything is working as described in your instructions, nice!

**Comment by C-Red20** [comment]
I can see the tags yay

**Review by sarahebrooks12 — CHANGES_REQUESTED** [review]
Almost! Make sure the sql query you give them would list the tags in alphabetical order. Just take the one that makes them show up from your repo and have them compare the tags on the browser to the ones listed in the sql query

**Review by sarahebrooks12 — APPROVED** [review]
Looks good!

**Pull request merged**
